[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_minter = "GgsbB7i8ruSheL5A5FkDf6upCbNgaXFURDiRdVtg2X6G"
srs_vault = "7qHxwJLfkiptAyxqYfoWEBsA9oampfGeGDhq3gpURZMn"

[programs.devnet]
nft_minter = "GgsbB7i8ruSheL5A5FkDf6upCbNgaXFURDiRdVtg2X6G"
srs_vault = "7qHxwJLfkiptAyxqYfoWEBsA9oampfGeGDhq3gpURZMn"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/mpl_core.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec vitest run --config .configs/vitest.config.ts"
